---
- hosts: localhost
  connection: local
  vars:
     vnode_prefix: vnode-
  roles:
    - role: laniakea.nfs

# server config example
# nfs_exports: [{path: "{{ nfs_server_export_dir }}", export: "{{ vnode_prefix }}*.localdomain(rw,async,no_root_squash,no_subtree_check,insecure)"}]

# client config example
# nfs_client_imports: [{ local: "{{ client_mountpoint }}", remote: "{{ nfs_server_export_dir }}", server_host: "{{ nfs_server_ip }}" }]
